# Basic shape rotation
Source: https://www.mathematics-monster.com/lessons/how_to_rotate_a_shape.html

In [2]:
import numpy as np
import pandas as pd


![Please refer to https://www.mathematics-monster.com/lessons/how_to_rotate_a_shape.html](../Assets/rotate1.png "Shape Rotation")

In [41]:
# Basic idea from https://stackoverflow.com/a/45649110/5820024
def to_rad(deg):
    return deg * np.pi / 180.


def sin(degrees):
    return np.sin(to_rad(degrees))


def cos(degrees):
    return np.cos(to_rad(degrees))


def rotate_point_old1(x, y, x_c, y_c, degrees, round_to=4):
    '''
    get the new point after rotation
    x, y: original coordinates of the point
    x_c, y_c: center of rotation's coordinates
    degrees: the rotation angle in degrees (+ve CCW, -ve CW)
    round_to: the rounding digits
    '''
    newx = (x - x_c) * cos(degrees) - (y - y_c) * sin(degrees) + x_c
    newy = (x - x_c) * sin(degrees) + (y - y_c) * cos(degrees) + y_c
    return np.round(np.array([newx, newy]), decimals=4).tolist()


def rotate_point_old2(x, y, x_c, y_c, degrees, round_to=4):
    '''
    get the new point after rotation
    x, y: original coordinates of the point
    x_c, y_c: center of rotation's coordinates
    degrees: the rotation angle in degrees (+ve CCW, -ve CW)
    round_to: the rounding digits
    '''
    rads = degrees * np.pi / 180.
    cr, sr = np.cos(rads), np.sin(rads)
    newx = (x - x_c) * cr - (y - y_c) * sr + x_c
    newy = (x - x_c) * sr + (y - y_c) * cr + y_c
    return np.round(np.array([newx, newy]), decimals=4).tolist()

def rotate_point(x, y, x_c, y_c, cr, sr, round_to=4):
    '''
    get the new point after rotation
    x, y: original coordinates of the point
    x_c, y_c: center of rotation's coordinates
    degrees: the rotation angle in degrees (+ve CCW, -ve CW)
    round_to: the rounding digits
    '''

    newx = (x - x_c) * cr - (y - y_c) * sr + x_c
    newy = (x - x_c) * sr + (y - y_c) * cr + y_c
    return np.round(np.array([newx, newy]), decimals=4).tolist()

***Notice that CW rotation is negative, while CCW rotation is positive***

In [45]:
# The given example rotation is NEGATIVE 60
rotate_point_old2(1, 4, 3, 1, -60)

[4.5981, 4.2321]

In [46]:
# Rotate back
rotate_point_old2(4.598076211353316, 4.232050807568878, 3, 1, 60)
rotate_point_old2(4.5981, 4.2321, 3, 1, 60)

[1.0, 4.0]

In [47]:
def rotate_shape_old(points, center, degrees, round_to=4):
    rotated=[]
    x_c, y_c = center
    
    for point in points:
        x, y = point
        new_point=tuple(rotate_point(x, y, x_c, y_c, degrees, round_to))
        rotated.append(new_point)
    return rotated

def rotate_shape(points, center, degrees, round_to=4):
    rotated=[]
    x_c, y_c = center
    rads = degrees * np.pi / 180.
    cr, sr = np.cos(rads), np.sin(rads)
    for point in points:
        x, y = point
        new_point=tuple(rotate_point(x, y, x_c, y_c, cr, sr, round_to))
        rotated.append(new_point)
    return rotated

In [48]:
rotate_shape(((1,4), (2, 6), (3, 4)), (3, 1), -60)

[(4.5981, 4.2321), (6.8301, 4.366), (5.5981, 2.5)]

#### Defining an array-based function

In [59]:
shape=np.array(((1,4), (2, 6), (3, 4)))
shape

array([[1, 4],
       [2, 6],
       [3, 4]])

In [52]:
center = (3, 1)
degrees = -60

rads = degrees * np.pi / 180.
cr, sr = np.cos(rads), np.sin(rads)
x_c, y_c = center

In [54]:

X, Y = shape[:,0], shape[:,1]
X, Y

(array([1, 2, 3]), array([4, 6, 4]))

In [60]:
new_shape = shape.copy()
X, Y = new_shape[:, 0], new_shape[:, 1]
print(X, Y)
X -= x_c
Y -= y_c
print(X, Y)

[1 2 3] [4 6 4]
[-2 -1  0] [3 5 3]


In [61]:
X, Y = X * cr - Y * sr + x_c, X * sr + Y * cr + y_c

print(X, Y)

[4.59807621 6.83012702 5.59807621] [4.23205081 4.3660254  2.5       ]


In [66]:
new_shape = np.vstack((X, Y)).T
new_shape

array([[4.59807621, 4.23205081],
       [6.83012702, 4.3660254 ],
       [5.59807621, 2.5       ]])

### Using metrices
https://math.stackexchange.com/questions/1917449/rotate-polygon-around-center-and-get-the-coordinates
![Please refer to https://math.stackexchange.com/questions/1917449/rotate-polygon-around-center-and-get-the-coordinates](../Assets/rotate2.png "Shape Rotation")

**[Another good source](https://matthew-brett.github.io/teaching/rotation_2d.html)**

In [83]:
# new_shape =
# C =np.array(((x_c), (y_c)))
C = np.array((x_c, y_c))
R = [[cr, -sr], [sr, cr]]

C, R

(array([3, 1]),
 [[0.5000000000000001, 0.8660254037844386],
  [-0.8660254037844386, 0.5000000000000001]])

In [87]:
new_shape = np.dot(R, (shape - C).T).T + C
new_shape

array([[4.59807621, 4.23205081],
       [6.83012702, 4.3660254 ],
       [5.59807621, 2.5       ]])

In [99]:
def array_rotate_2D(cords, center, degrees):
    '''
    To find the new coordinates of the rotated shape
    cords: the original coordinates (numpy array of 2 columns (x,y) and n rows)
    center: the x, y coordinates of the point of rotation
    degrees: the angle of rotation (+ve CCW, -ve CW)
    '''
    rads = degrees * np.pi / 180.
    cr, sr = np.cos(rads), np.sin(rads)
    # x_c, y_c = center
    C = np.array(center)  #np.array((x_c, y_c))
    R = [[cr, -sr], [sr, cr]]
    return np.dot(R, (cords - C).T).T + C


# Test
display(shape, center, degrees)
array_rotate_2D(shape, center, degrees)

array([[1, 4],
       [2, 6],
       [3, 4]])

(3, 1)

-60

array([[4.59807621, 4.23205081],
       [6.83012702, 4.3660254 ],
       [5.59807621, 2.5       ]])

## Shape rotation in 3D across X, Y, or Z axes

[The source of formulas](https://stackoverflow.com/a/14609567/5820024), [and a thorough description of rules is here](https://en.wikipedia.org/wiki/Rotation_matrix)

In [103]:
def array_rotate_3D(cords, degrees, rotation_axis='X'):
    '''
    To find the new coordinates of the rotated shape
    The shape here is rotated with ONE angle on ONE axis only.
    
    cords: the original coordinates 
            (a numpy array of 3 columns (x, y, z) and n rows)
    degrees: the angle of rotation (+ve CCW, -ve CW)
    rotation_axis='X' or 'Y' or 'Z'
    '''
    rads = degrees * np.pi / 180.
    cr, sr = np.cos(rads), np.sin(rads)
    # x_c, y_c = center
    C = np.array(center)  #np.array((x_c, y_c))
    ax = rotation_axis.lower()
    if ax == 'x':
        R = [[1, 0, 0], [0, cr, -sr], [0, sr, cr]]
    elif ax == 'y':
        R = [[cr, 0, sr], [0, 1, 0], [-sr, 0, cr]]
    elif ax == 'z':
        R = [[cr, -sr, 0], [sr, cr, 0], [0, 0, 1]]
    else:  # Other
        print(f'Axis {rotation_axis} is not recognized!')
        raise ()

    # display(R, cords.T)
    return np.dot(R, cords.T).T

In [104]:
shape3D1 = np.array(((1, 4, 2), (2, 6, 2), (3, 4, 2)))
shape3D2 = np.array(((1, 4, 2), (2, 6, 3), (3, 4, 4)))
display(shape3D1,  shape3D2)

array([[1, 4, 2],
       [2, 6, 2],
       [3, 4, 2]])

array([[1, 4, 2],
       [2, 6, 3],
       [3, 4, 4]])

In [105]:
array_rotate_3D(shape3D1, -60, rotation_axis='Z')

array([[ 3.96410162,  1.1339746 ,  2.        ],
       [ 6.19615242,  1.26794919,  2.        ],
       [ 4.96410162, -0.59807621,  2.        ]])

In [106]:
array_rotate_2D(shape, (0, 0), degrees)

array([[ 3.96410162,  1.1339746 ],
       [ 6.19615242,  1.26794919],
       [ 4.96410162, -0.59807621]])

In [107]:
array_rotate_3D(shape3D1, -60, rotation_axis='Y')

array([[-1.23205081,  4.        ,  1.8660254 ],
       [-0.73205081,  6.        ,  2.73205081],
       [-0.23205081,  4.        ,  3.59807621]])

In [108]:
array_rotate_3D(shape3D1, -60, rotation_axis='x')

array([[ 1.        ,  3.73205081, -2.46410162],
       [ 2.        ,  4.73205081, -4.19615242],
       [ 3.        ,  3.73205081, -2.46410162]])

In [109]:
array_rotate_3D(shape3D2, -60, rotation_axis='Z')

array([[ 3.96410162,  1.1339746 ,  2.        ],
       [ 6.19615242,  1.26794919,  3.        ],
       [ 4.96410162, -0.59807621,  4.        ]])