In [1]:
import os
import glob
import shutil
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap as LSCm
from scipy.interpolate import griddata
from scipy.signal import savgol_filter
from scipy import integrate
from NesrHydrusAnalyst import *

In [3]:
src = '../Datasets/H3D2_SandDitch0011'

# Working with velocity

In [8]:
df= read_hydrus_data(folder=src, save_to_csv=False, read_velocities=True)
df.sample(3)

n        x        y         z  Th_T0     Th_T5    Th_T15    Th_T30  \
4404  4404  10.0515  13.7500  12.19070   0.20  0.200000  0.200000  0.200000   
1944  1944  27.2782  18.4615   6.09483   0.15  0.230054  0.245116  0.265845   
6545  6545  46.5295   6.2500  11.78960   0.20  0.200000  0.200000  0.200000   

        Th_T60   Th_T120  ...   V3_T240   V1_T500   V2_T500   V3_T500  \
4404  0.200000  0.200028  ... -0.000015 -0.000030 -0.000006 -0.000089   
1944  0.390000  0.372977  ... -0.000105  0.000027 -0.000002 -0.000068   
6545  0.200006  0.204638  ... -0.000242  0.000014  0.000006 -0.000272   

           V1_T720   V2_T720   V3_T720  V1_T1440  V2_T1440  V3_T1440  
4404 -9.619570e-05 -0.000007 -0.000076 -0.000080 -0.000002  0.000004  
1944 -8.586860e-07 -0.000002 -0.000058 -0.000020 -0.000002 -0.000031  
6545  1.930540e-05  0.000005 -0.000132  0.000007  0.000001 -0.000049  

[3 rows x 59 columns]

In [9]:
print(list(df))

['n', 'x', 'y', 'z', 'Th_T0', 'Th_T5', 'Th_T15', 'Th_T30', 'Th_T60', 'Th_T120', 'Th_T180', 'Th_T240', 'Th_T500', 'Th_T720', 'Th_T1440', 'H_T0', 'H_T5', 'H_T15', 'H_T30', 'H_T60', 'H_T120', 'H_T180', 'H_T240', 'H_T500', 'H_T720', 'H_T1440', 'V1_T0', 'V2_T0', 'V3_T0', 'V1_T5', 'V2_T5', 'V3_T5', 'V1_T15', 'V2_T15', 'V3_T15', 'V1_T30', 'V2_T30', 'V3_T30', 'V1_T60', 'V2_T60', 'V3_T60', 'V1_T120', 'V2_T120', 'V3_T120', 'V1_T180', 'V2_T180', 'V3_T180', 'V1_T240', 'V2_T240', 'V3_T240', 'V1_T500', 'V2_T500', 'V3_T500', 'V1_T720', 'V2_T720', 'V3_T720', 'V1_T1440', 'V2_T1440', 'V3_T1440']


In [11]:
df.describe().T

count          mean          std         min           25%  \
n         8250.0  4.125500e+03  2381.714194    1.000000  2.063250e+03   
x         8250.0  2.451462e+01    14.887410   -0.839105  1.155150e+01   
y         8250.0  9.983508e+00     6.314130    0.000000  4.615380e+00   
z         8250.0  1.186658e+01     6.483165    0.000000  6.190740e+00   
Th_T0     8250.0  1.778485e-01     0.034929    0.100000  1.500000e-01   
Th_T5     8250.0  1.886862e-01     0.066437    0.049132  1.999210e-01   
Th_T15    8250.0  2.104914e-01     0.086384    0.049792  2.000000e-01   
Th_T30    8250.0  2.355983e-01     0.097230    0.049960  2.000000e-01   
Th_T60    8250.0  2.954227e-01     0.100979    0.049914  2.000060e-01   
Th_T120   8250.0  2.915740e-01     0.075816    0.133659  2.084185e-01   
Th_T180   8250.0  2.897240e-01     0.075875    0.114704  2.090897e-01   
Th_T240   8250.0  2.883644e-01     0.076297    0.103804  2.263487e-01   
Th_T500   8250.0  2.853139e-01     0.079861    0.083541  2.692193e-01   
Th_T720   8250.0  2.841839e-01     0.083095    0.076450  2.675612e-01   
Th_T1440  8250.0  2.829693e-01     0.088163    0.068080  2.889022e-01   
H_T0      8250.0 -1.721454e+02   170.251951 -676.912000 -1.562710e+02   
H_T5      8250.0 -1.177817e+02    58.573060 -408.734000 -1.562710e+02   
H_T15     8250.0 -1.073059e+02    63.323097 -367.125000 -1.562710e+02   
H_T30     8250.0 -9.457167e+01    67.678309 -316.477000 -1.562710e+02   
H_T60     8250.0 -6.524594e+01    70.796241 -223.102000 -1.561457e+02   
H_T120    8250.0 -4.400701e+01    55.368267 -156.301000 -5.997578e+01   
H_T180    8250.0 -3.647210e+01    46.444367 -156.272000 -3.588355e+01   
H_T240    8250.0 -3.172238e+01    39.063472 -156.234000 -2.853475e+01   
H_T500    8250.0 -2.294017e+01    19.178251 -143.650000 -2.409013e+01   
H_T720    8250.0 -2.090900e+01    11.325674  -95.249300 -2.292643e+01   
H_T1440   8250.0 -2.000327e+01     6.853990  -37.169000 -2.446405e+01   
V1_T0     8250.0 -1.150904e-04     0.097759   -0.775172 -3.632887e-13   
V2_T0     8250.0  6.151919e-05     0.015690   -0.263769 -6.682525e-13   
V3_T0     8250.0  3.262245e-02     0.147322   -0.342545 -1.845390e-05   
V1_T5     8250.0 -2.912501e-02     0.174308   -1.652350 -4.644788e-07   
V2_T5     8250.0 -1.117886e-03     0.008151   -0.185107 -1.977383e-07   
V3_T5     8250.0 -6.567916e-03     0.061332   -1.086420 -1.361290e-05   
V1_T15    8250.0 -6.323760e-02     0.250161   -1.656050 -6.268082e-06   
V2_T15    8250.0 -9.910325e-04     0.007840   -0.184093 -4.202597e-07   
V3_T15    8250.0 -1.116437e-02     0.066147   -1.081890 -1.300265e-04   
V1_T30    8250.0 -6.812832e-02     0.259028   -1.659350 -4.749207e-05   
V2_T30    8250.0 -8.348018e-04     0.007770   -0.183381 -4.840132e-07   
V3_T30    8250.0 -2.021711e-02     0.084864   -1.078040 -1.685968e-03   
V1_T60    8250.0 -7.945114e-02     0.278425   -1.660930 -1.274243e-03   
V2_T60    8250.0 -7.721850e-04     0.007899   -0.183243 -6.559262e-06   
V3_T60    8250.0 -2.430537e-02     0.087434   -1.075670 -6.939015e-03   
V1_T120   8250.0 -8.377398e-04     0.009865   -0.060200 -3.690030e-04   
V2_T120   8250.0  3.506788e-06     0.000159   -0.002932 -8.417865e-06   
V3_T120   8250.0 -9.821593e-04     0.004322   -0.027901 -1.088245e-03   
V1_T180   8250.0 -4.272027e-04     0.004172   -0.025940 -2.453840e-04   
V2_T180   8250.0  2.505054e-06     0.000072   -0.001311 -6.337870e-06   
V3_T180   8250.0 -3.674908e-04     0.001810   -0.010701 -7.087292e-04   
V1_T240   8250.0 -2.873808e-04     0.002574   -0.016447 -2.075815e-04   
V2_T240   8250.0  2.581709e-06     0.000046   -0.000778 -4.660510e-06   
V3_T240   8250.0 -1.967703e-04     0.001092   -0.006044 -5.371485e-04   
V1_T500   8250.0 -1.028705e-04     0.000892   -0.005891 -1.051995e-04   
V2_T500   8250.0  1.959102e-06     0.000015   -0.000224 -1.431972e-06   
V3_T500   8250.0 -4.691962e-05     0.000368   -0.001705 -2.277015e-04   
V1_T720   8250.0 -7.777350e-05     0.000561   -0.003842 -7.629937e-05

## The velocity components:
![From HYDRUS simulation](../Assets/H_velocity.png)
**V1 is the _x_ complonent of the velocity.**<br>
**V2 is the _y_ complonent of the velocity.**<br>
**V3 is the _z_ complonent of the velocity.**<br>


In [14]:
vr = 0
# v_mask = {0: 'Th', 1: 'H', 2.1:'V1', 2.2:'V2', 2.3:'V3'}[variable]
X, Z, M, x_vals, z_vals = get_grid_values(df, variable=vr)

# display(get_available_timesteps(df),
#         get_full_dimensions(data_frame),
#         get_legend_range(M.min(), M.max()),
#         'x_vals{}, z_vals{}, X{}, Z{}, M{}'.format(x_vals.shape, z_vals.shape,
#                                                    X.shape, Z.shape, M.shape))
X, Z, M, x_vals, z_vals

(array([[0.000, 0.500, 1.000, ..., 19.000, 19.500, 20.000],
        [0.000, 0.500, 1.000, ..., 19.000, 19.500, 20.000],
        [0.000, 0.500, 1.000, ..., 19.000, 19.500, 20.000],
        ...,
        [0.000, 0.500, 1.000, ..., 19.000, 19.500, 20.000],
        [0.000, 0.500, 1.000, ..., 19.000, 19.500, 20.000],
        [0.000, 0.500, 1.000, ..., 19.000, 19.500, 20.000]]),
 array([[0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000],
        [0.511, 0.511, 0.511, ..., 0.511, 0.511, 0.511],
        [1.021, 1.021, 1.021, ..., 1.021, 1.021, 1.021],
        ...,
        [21.960, 21.960, 21.960, ..., 21.960, 21.960, 21.960],
        [22.470, 22.470, 22.470, ..., 22.470, 22.470, 22.470],
        [22.981, 22.981, 22.981, ..., 22.981, 22.981, 22.981]]),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [0.184, 0.184, 0.184, ..., 0.184, 0.184, 0.184],
        [nan, nan, nan, ..., nan, nan, nan],


In [15]:
get_available_timesteps(df)

IndexError: list index out of range